# Generated by Django 6.0.4 on 2026-07-27 16:17

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='api_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_status_code', models.IntegerField()),
                ('api_response_text', models.TextField()),
                ('api_response_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ml_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('access_token', encrypted_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('shipping_id', models.CharField(blank=True, max_length=100)),
                ('logistic_type', models.CharField(blank=True, choices=[('collect', 'ML Colecta'), ('flex', 'ML Flex')], max_length=20)),
                ('client_nickname', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('ready_to_print', 'ready_to_print'), ('ready_to_ship', 'ready_to_ship'), ('preparing', 'Preparando'), ('not_prepared', 'No preparado'), ('partially_prepared', 'Parcialmente preparado'), ('prepared', 'Preparado')], max_length=20)),
                ('creation_date_time', models.DateTimeField(null=True)),
                ('estimated_pickup_time', models.DateTimeField(null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_seller', models.CharField(blank=True, max_length=100)),
                ('sku_marketplace', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_scanned', models.IntegerField(default=0)),
                ('prepared_without_stock', models.BooleanField(default=False)),
                ('creation_date_time', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='orders_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('processed', 'processed'), ('dispatched', 'dispatched')], default='in_progress', max_length=20)),
                ('logistic_type', models.CharField(blank=True, choices=[('collect', 'ML Colecta'), ('flex', 'ML Flex')], max_length=20, null=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('processed_date_time', models.DateTimeField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=60)),
                ('courier_license_plate', models.CharField(blank=True, max_length=6)),
                ('manifest_image', models.ImageField(blank=True, upload_to='')),
                ('dispatched_date_time', models.DateTimeField(blank=True, null=True)),
                ('dispatched_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.marketplace')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orders_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders_group'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_id', 'marketplace'), name='unique_order_per_marketplace'),
        ),
    ]
