# Generated by Django 6.0.4 on 2026-04-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('shipping_id', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(blank=True, choices=[('collect', 'ML Colecta'), ('flex', 'ML Flex')], max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('creation_date_time', models.DateTimeField(null=True)),
                ('estimated_pickup_time', models.DateTimeField(null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_seller', models.CharField(blank=True, max_length=100)),
                ('sku_marketplace', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
