# Generated by Django 6.0.4 on 2026-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_group',
            name='courier_license_plate',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='orders_group',
            name='courier_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='orders_group',
            name='manifest_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
