# Generated by Django 6.0.4 on 2026-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('collect', 'ML Colecta'), ('flex', 'ML Flex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ready_to_print', 'ready_to_print'), ('ready_to_ship', 'ready_to_ship')], max_length=20),
        ),
    ]
