# Generated by Django 6.0.4 on 2026-07-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_group_courier_license_plate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_group',
            old_name='dispatched_date_time',
            new_name='finalized_date_time',
        ),
        migrations.RemoveField(
            model_name='orders_group',
            name='dispatched_by',
        ),
        migrations.AddField(
            model_name='orders_group',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders_group',
            name='finalized_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='finalized_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders_group',
            name='processed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders_group',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('processed', 'processed'), ('finalized', 'finalized')], default='in_progress', max_length=20),
        ),
    ]
