# Generated by Django 6.0.4 on 2026-05-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ml_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='client_nickname',
        ),
    ]
