# Generated by Django 6.0.4 on 2026-07-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_dispatched_date_time_orders_group_finalized_date_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_group',
            old_name='processed_date_time',
            new_name='prepared_date_time',
        ),
        migrations.RemoveField(
            model_name='orders_group',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='orders_group',
            name='prepared_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='prepared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders_group',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('prepared', 'prepared'), ('finalized', 'finalized')], default='in_progress', max_length=20),
        ),
    ]
