# Generated by Django 6.0.4 on 2026-06-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_client_name_order_client_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='logistic_type',
        ),
    ]
