# Generated by Django 6.0.4 on 2026-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_processed_date_time_orders_group_prepared_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='seller_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
