# Generated by Django 6.0.4 on 2026-06-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_order_type_order_logistic_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_id', 'marketplace'), name='unique_order_per_marketplace'),
        ),
    ]
