# Generated by Django 6.0.4 on 2026-08-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_product_seller_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='direct_orders_update_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date_time', models.DateTimeField(null=True)),
                ('finished', models.BooleanField(default=False)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.marketplace')),
            ],
        ),
    ]
