# Generated by Django 6.0.4 on 2026-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_direct_orders_update_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct_orders_update_log',
            name='update_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
