# Generated by Django 6.0.4 on 2026-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_unique_order_per_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_status_code', models.IntegerField()),
                ('api_response_text', models.TextField()),
                ('api_response_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
