# Generated by Django 6.0.4 on 2026-06-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_api_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='creation_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='orders_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('processed', 'processed')], default='in_progress', max_length=20)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('processed_date_time', models.DateTimeField(null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.marketplace')),
            ],
        ),
    ]
