# Generated by Django 6.0.4 on 2026-08-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_direct_orders_update_log_update_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='creation_date_time',
        ),
    ]
