# Generated by Django 6.0.4 on 2026-06-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_product_creation_date_time_orders_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders_group'),
        ),
    ]
