# Generated by Django 6.0.4 on 2026-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_orders_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ready_to_print', 'ready_to_print'), ('ready_to_ship', 'ready_to_ship'), ('preparing', 'preparing')], max_length=20),
        ),
    ]
