# Generated by Django 6.0.4 on 2026-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='quantity_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
