# Generated by Django 6.0.4 on 2026-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_product_quantity_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_group',
            name='logistic_type',
            field=models.CharField(blank=True, choices=[('collect', 'ML Colecta'), ('flex', 'ML Flex')], max_length=20, null=True),
        ),
    ]
