# Generated by Django 6.0.4 on 2026-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_group_logistic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_group',
            name='processed_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
