# Generated by Django 6.0.4 on 2026-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orders_group_processed_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ready_to_print', 'ready_to_print'), ('ready_to_ship', 'ready_to_ship'), ('preparing', 'Preparando'), ('prepared', 'Preparado')], max_length=20),
        ),
    ]
