# Generated by Django 6.0.4 on 2026-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ready_to_print', 'ready_to_print'), ('ready_to_ship', 'ready_to_ship'), ('preparing', 'Preparando'), ('not_prepared', 'No preparado'), ('partially_prepared', 'Parcialmente preparado'), ('prepared', 'Preparado')], max_length=20),
        ),
    ]
