# Generated by Django 6.0.4 on 2026-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='prepared_without_stock',
            field=models.BooleanField(default=False),
        ),
    ]
