# Generated by Django 6.0.4 on 2026-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_derivated_sku_sku_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivated_sku',
            name='sku',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
