# Generated by Django 6.0.4 on 2026-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_derivated_sku_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivated_sku',
            name='sku',
            field=models.CharField(default=3, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
