# Generated by Django 6.0.4 on 2026-07-28 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'El EAN debe tener exactamente 13 dígitos numéricos.')]),
        ),
    ]
