# Generated by Django 6.0.4 on 2026-08-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
